/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_admin (void);
GtkWidget* create_userlist (void);
GtkWidget* create_stafflist (void);
GtkWidget* create_eventslist_admin (void);
GtkWidget* create_bienvenue_coach (void);
GtkWidget* create_profil_coach (void);
GtkWidget* create_seance_coach (void);
GtkWidget* create_fiche_m__dicale_coach (void);
GtkWidget* create_bienvenue_kine (void);
GtkWidget* create_profil_kine (void);
GtkWidget* create_dispo_kine (void);
GtkWidget* create_fiche_med_kine (void);
GtkWidget* create_seance_kine (void);
GtkWidget* create_liste_des_adh_coach (void);
GtkWidget* create_bienvenue_medecin (void);
GtkWidget* create_profil_medecin (void);
GtkWidget* create_dispo_medecin (void);
GtkWidget* create_fiche_med_medecin (void);
GtkWidget* create_rendez_vous_medecin (void);
GtkWidget* create_diet (void);
GtkWidget* create_dispo_diet (void);
GtkWidget* create_rdv_diet (void);
GtkWidget* create_ficheal_diet (void);
GtkWidget* create_profil_diet (void);
GtkWidget* create_adherant (void);
GtkWidget* create_rendez_vous (void);
GtkWidget* create_espace_medicale (void);
GtkWidget* create_evennements (void);
GtkWidget* create_affichage_evennement (void);
GtkWidget* create_ajout_rdv (void);
GtkWidget* create_modification_profil_adherant (void);
