/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *button1;
  GtkWidget *label3;
  GtkWidget *label15;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (login, 450, 460);
  gtk_window_set_title (GTK_WINDOW (login), _("Login"));
  gtk_window_set_position (GTK_WINDOW (login), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_gravity (GTK_WINDOW (login), GDK_GRAVITY_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (login), fixed1);
  gtk_widget_set_size_request (fixed1, 410, 600);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 64, 160);
  gtk_widget_set_size_request (entry1, 344, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 64, 240);
  gtk_widget_set_size_request (entry2, 344, 30);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label1 = gtk_label_new (_("<span size=\"large\" color=\"blue\">Nom d'utilisateur</span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 55, 125);
  gtk_widget_set_size_request (label1, 160, 30);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  label2 = gtk_label_new (_("<span size=\"large\" color=\"blue\">Mot de passe</span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 54, 205);
  gtk_widget_set_size_request (label2, 130, 30);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  button1 = gtk_button_new_with_mnemonic (_("Connexion"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 64, 298);
  gtk_widget_set_size_request (button1, 344, 40);

  label3 = gtk_label_new (_("Si vous rencontrez des difficult\303\251s \303\240 vous connecter\n \303\240 votre espace, Veuillez contacter l'administrateur\n                               pour obtenir de l'aide."));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 64, 365);
  gtk_widget_set_size_request (label3, 346, 80);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  label15 = gtk_label_new (_("<span size=\"xx-large\" color=\"red\"><b>Connexion</b></span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed1), label15, 152, 24);
  gtk_widget_set_size_request (label15, 137, 64);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (login, label1, "label1");
  GLADE_HOOKUP_OBJECT (login, label2, "label2");
  GLADE_HOOKUP_OBJECT (login, button1, "button1");
  GLADE_HOOKUP_OBJECT (login, label3, "label3");
  GLADE_HOOKUP_OBJECT (login, label15, "label15");

  return login;
}

GtkWidget*
create_bienvenue (void)
{
  GtkWidget *bienvenue;
  GtkWidget *fixed2;
  GtkWidget *label9;
  GtkWidget *button18m;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *label6;
  GtkWidget *fixed4;
  GtkWidget *calendar1;
  GtkWidget *label7;
  GtkWidget *fixed8;
  GtkWidget *treeview1;
  GtkWidget *button7;
  GtkWidget *label61;
  GtkWidget *button9;
  GtkWidget *button8;
  GtkWidget *button17;
  GtkWidget *fixed12m;
  GtkWidget *treeview4m;
  GtkWidget *button19ms;
  GtkWidget *button18ms;

  bienvenue = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (bienvenue, 850, 700);
  gtk_window_set_title (GTK_WINDOW (bienvenue), _("Bienvenue"));
  gtk_window_set_position (GTK_WINDOW (bienvenue), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_gravity (GTK_WINDOW (bienvenue), GDK_GRAVITY_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (bienvenue), fixed2);

  label9 = gtk_label_new (_("<span size=\"x-large\" color=\"red\">Espace Kin\303\251sith\303\251rapeute</span>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 304, 40);
  gtk_widget_set_size_request (label9, 256, 30);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  button18m = gtk_button_new_with_mnemonic (_("D\303\251conexion"));
  gtk_widget_show (button18m);
  gtk_fixed_put (GTK_FIXED (fixed2), button18m, 744, 16);
  gtk_widget_set_size_request (button18m, 94, 29);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 112);
  gtk_widget_set_size_request (notebook1, 872, 600);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  label6 = gtk_label_new (_("Profile"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label6);
  gtk_widget_set_size_request (label6, 80, 30);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed4), calendar1, 128, 48);
  gtk_widget_set_size_request (calendar1, 592, 408);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label7 = gtk_label_new (_("Agenda"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label7);
  gtk_widget_set_size_request (label7, 80, 30);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview1, 0, 0);
  gtk_widget_set_size_request (treeview1, 856, 440);

  button7 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed8), button7, 60, 480);
  gtk_widget_set_size_request (button7, 90, 35);

  label61 = gtk_label_new ("");
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed8), label61, 592, 480);
  gtk_widget_set_size_request (label61, 145, 46);

  button9 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed8), button9, 380, 480);
  gtk_widget_set_size_request (button9, 90, 35);

  button8 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed8), button8, 220, 480);
  gtk_widget_set_size_request (button8, 90, 35);

  button17 = gtk_button_new_with_mnemonic (_("Calendrier"));
  gtk_widget_show (button17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), button17);
  gtk_widget_set_size_request (button17, 86, 29);

  fixed12m = gtk_fixed_new ();
  gtk_widget_show (fixed12m);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12m);

  treeview4m = gtk_tree_view_new ();
  gtk_widget_show (treeview4m);
  gtk_fixed_put (GTK_FIXED (fixed12m), treeview4m, 0, 0);
  gtk_widget_set_size_request (treeview4m, 840, 440);

  button19ms = gtk_button_new_with_mnemonic (_("Modifier remarques"));
  gtk_widget_show (button19ms);
  gtk_fixed_put (GTK_FIXED (fixed12m), button19ms, 72, 472);
  gtk_widget_set_size_request (button19ms, 170, 47);

  button18ms = gtk_button_new_with_mnemonic (_("Consulter fiche medical"));
  gtk_widget_show (button18ms);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), button18ms);

  g_signal_connect ((gpointer) button18m, "clicked",
                    G_CALLBACK (on_button18m_clicked),
                    NULL);
  g_signal_connect ((gpointer) calendar1, "day_selected_double_click",
                    G_CALLBACK (on_calendar1_day_selected_double_click),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19ms, "clicked",
                    G_CALLBACK (on_button19ms_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18ms, "clicked",
                    G_CALLBACK (on_button18ms_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bienvenue, bienvenue, "bienvenue");
  GLADE_HOOKUP_OBJECT (bienvenue, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (bienvenue, label9, "label9");
  GLADE_HOOKUP_OBJECT (bienvenue, button18m, "button18m");
  GLADE_HOOKUP_OBJECT (bienvenue, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (bienvenue, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (bienvenue, label6, "label6");
  GLADE_HOOKUP_OBJECT (bienvenue, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (bienvenue, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (bienvenue, label7, "label7");
  GLADE_HOOKUP_OBJECT (bienvenue, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (bienvenue, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (bienvenue, button7, "button7");
  GLADE_HOOKUP_OBJECT (bienvenue, label61, "label61");
  GLADE_HOOKUP_OBJECT (bienvenue, button9, "button9");
  GLADE_HOOKUP_OBJECT (bienvenue, button8, "button8");
  GLADE_HOOKUP_OBJECT (bienvenue, button17, "button17");
  GLADE_HOOKUP_OBJECT (bienvenue, fixed12m, "fixed12m");
  GLADE_HOOKUP_OBJECT (bienvenue, treeview4m, "treeview4m");
  GLADE_HOOKUP_OBJECT (bienvenue, button19ms, "button19ms");
  GLADE_HOOKUP_OBJECT (bienvenue, button18ms, "button18ms");

  return bienvenue;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed7;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label26;
  GtkWidget *label28;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *combobox8;
  GtkWidget *combobox3;
  GtkWidget *combobox5;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 850, 700);
  gtk_window_set_title (GTK_WINDOW (window2), _("ajouter"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER_ALWAYS);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window2), fixed7);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton4, 90, 195);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton5, 245, 195);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (2018, 2018, 2050, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton6, 405, 195);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label26 = gtk_label_new ("");
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 312, 168);
  gtk_widget_set_size_request (label26, 136, 17);

  label28 = gtk_label_new ("");
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed7), label28, 424, 608);
  gtk_widget_set_size_request (label28, 242, 20);

  button5 = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed7), button5, 688, 600);
  gtk_widget_set_size_request (button5, 90, 35);

  button6 = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed7), button6, 112, 600);
  gtk_widget_set_size_request (button6, 90, 35);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox8, 162, 470);
  gtk_widget_set_size_request (combobox8, 375, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("S\303\251ance_de_r\303\251\303\251ducation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Rendez_vous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Cong\303\251_annuel"));

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox3, 112, 336);
  gtk_widget_set_size_request (combobox3, 208, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("17"));

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox5, 424, 336);
  gtk_widget_set_size_request (combobox5, 208, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("18"));

  label30 = gtk_label_new (_("<span foreground=\"red\" size=\"xx-large\"><b>Ajouter un \303\251v\303\251nement</b></span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed7), label30, 264, 48);
  gtk_widget_set_size_request (label30, 328, 33);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label31 = gtk_label_new (_("<span foreground=\"blue\" size=\"large\">Date de \303\251venement</span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed7), label31, 24, 144);
  gtk_widget_set_size_request (label31, 184, 25);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label32 = gtk_label_new (_("<span foreground=\"blue\" size=\"large\">Heure de l'\303\251venement</span>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed7), label32, 22, 280);
  gtk_widget_set_size_request (label32, 216, 32);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  label33 = gtk_label_new (_("<span foreground=\"blue\" size=\"large\">\303\211v\303\251nement</span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed7), label33, 16, 472);
  gtk_widget_set_size_request (label33, 148, 26);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label34 = gtk_label_new (_("<b>D\303\251but</b>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed7), label34, 40, 344);
  gtk_widget_set_size_request (label34, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label35 = gtk_label_new (_("<b>Fin</b>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed7), label35, 352, 344);
  gtk_widget_set_size_request (label35, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  label23 = gtk_label_new (_("<b>jour</b>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed7), label23, 15, 200);
  gtk_widget_set_size_request (label23, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("<b>mois</b>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed7), label24, 170, 200);
  gtk_widget_set_size_request (label24, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<b>ann\303\251e</b>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 325, 200);
  gtk_widget_set_size_request (label25, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) combobox3, "changed",
                    G_CALLBACK (on_combobox3_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window2, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window2, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window2, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window2, label26, "label26");
  GLADE_HOOKUP_OBJECT (window2, label28, "label28");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");
  GLADE_HOOKUP_OBJECT (window2, button6, "button6");
  GLADE_HOOKUP_OBJECT (window2, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (window2, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (window2, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (window2, label30, "label30");
  GLADE_HOOKUP_OBJECT (window2, label31, "label31");
  GLADE_HOOKUP_OBJECT (window2, label32, "label32");
  GLADE_HOOKUP_OBJECT (window2, label33, "label33");
  GLADE_HOOKUP_OBJECT (window2, label34, "label34");
  GLADE_HOOKUP_OBJECT (window2, label35, "label35");
  GLADE_HOOKUP_OBJECT (window2, label23, "label23");
  GLADE_HOOKUP_OBJECT (window2, label24, "label24");
  GLADE_HOOKUP_OBJECT (window2, label25, "label25");

  return window2;
}

GtkWidget*
create_admin1 (void)
{
  GtkWidget *admin1;
  GtkWidget *_1fixed10;
  GtkWidget *label42;
  GtkWidget *_1notebook2;
  GtkWidget *empty_notebook_page;
  GtkWidget *label43;
  GtkWidget *fixed10;
  GtkWidget *treeview3;
  GtkWidget *button13;
  GtkWidget *button14;
  GtkWidget *button12;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;

  admin1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (admin1, 850, 700);
  gtk_window_set_title (GTK_WINDOW (admin1), _("Admin"));
  gtk_window_set_position (GTK_WINDOW (admin1), GTK_WIN_POS_CENTER_ALWAYS);

  _1fixed10 = gtk_fixed_new ();
  gtk_widget_show (_1fixed10);
  gtk_container_add (GTK_CONTAINER (admin1), _1fixed10);

  label42 = gtk_label_new (_("Espace Administrateur"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (_1fixed10), label42, 344, 40);
  gtk_widget_set_size_request (label42, 157, 17);

  _1notebook2 = gtk_notebook_new ();
  gtk_widget_show (_1notebook2);
  gtk_fixed_put (GTK_FIXED (_1fixed10), _1notebook2, 0, 112);
  gtk_widget_set_size_request (_1notebook2, 872, 600);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (_1notebook2), empty_notebook_page);

  label43 = gtk_label_new (_("Profil"));
  gtk_widget_show (label43);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (_1notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (_1notebook2), 0), label43);
  gtk_widget_set_size_request (label43, -1, 24);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (_1notebook2), fixed10);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview3, 0, 0);
  gtk_widget_set_size_request (treeview3, 848, 456);

  button13 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed10), button13, 220, 480);
  gtk_widget_set_size_request (button13, 90, 35);

  button14 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed10), button14, 380, 480);
  gtk_widget_set_size_request (button14, 90, 35);

  button12 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed10), button12, 56, 480);
  gtk_widget_set_size_request (button12, 90, 35);

  label37 = gtk_label_new (_("Gestion Des Adh\303\251rents"));
  gtk_widget_show (label37);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (_1notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (_1notebook2), 1), label37);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (_1notebook2), empty_notebook_page);

  label38 = gtk_label_new (_("Gestion des coachs"));
  gtk_widget_show (label38);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (_1notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (_1notebook2), 2), label38);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (_1notebook2), empty_notebook_page);

  label39 = gtk_label_new (_("Gestion de l'espace m\303\251dicale"));
  gtk_widget_show (label39);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (_1notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (_1notebook2), 3), label39);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (_1notebook2), empty_notebook_page);

  label40 = gtk_label_new (_("Gestion du site"));
  gtk_widget_show (label40);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (_1notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (_1notebook2), 4), label40);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_ajoutad_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin1, admin1, "admin1");
  GLADE_HOOKUP_OBJECT (admin1, _1fixed10, "_1fixed10");
  GLADE_HOOKUP_OBJECT (admin1, label42, "label42");
  GLADE_HOOKUP_OBJECT (admin1, _1notebook2, "_1notebook2");
  GLADE_HOOKUP_OBJECT (admin1, label43, "label43");
  GLADE_HOOKUP_OBJECT (admin1, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (admin1, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (admin1, button13, "button13");
  GLADE_HOOKUP_OBJECT (admin1, button14, "button14");
  GLADE_HOOKUP_OBJECT (admin1, button12, "button12");
  GLADE_HOOKUP_OBJECT (admin1, label37, "label37");
  GLADE_HOOKUP_OBJECT (admin1, label38, "label38");
  GLADE_HOOKUP_OBJECT (admin1, label39, "label39");
  GLADE_HOOKUP_OBJECT (admin1, label40, "label40");

  return admin1;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed11;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *entry11;
  GtkWidget *label58;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label47;
  GtkWidget *button15;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *combobox7;
  GtkWidget *combobox6;
  GtkWidget *button16;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window3, 850, 700);
  gtk_window_set_title (GTK_WINDOW (window3), _("Ajout d'Adh\303\251rent"));
  gtk_window_set_position (GTK_WINDOW (window3), GTK_WIN_POS_CENTER_ALWAYS);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window3), fixed11);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed11), entry5, 272, 250);
  gtk_widget_set_size_request (entry5, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed11), entry6, 272, 200);
  gtk_widget_set_size_request (entry6, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed11), entry7, 272, 400);
  gtk_widget_set_size_request (entry7, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed11), entry8, 272, 300);
  gtk_widget_set_size_request (entry8, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton7, 320, 496);
  gtk_widget_set_size_request (spinbutton7, 48, 24);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spinbutton7), GTK_UPDATE_IF_VALID);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton8, 448, 496);
  gtk_widget_set_size_request (spinbutton8, 48, 24);

  spinbutton9_adj = gtk_adjustment_new (2018, 0, 2018, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton9, 584, 496);
  gtk_widget_set_size_request (spinbutton9, 64, 24);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed11), label44, 456, 160);
  gtk_widget_set_size_request (label44, 128, 25);

  label45 = gtk_label_new ("");
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed11), label45, 464, 240);
  gtk_widget_set_size_request (label45, 128, 24);

  label46 = gtk_label_new ("");
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed11), label46, 464, 280);
  gtk_widget_set_size_request (label46, 112, 25);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed11), entry11, 272, 450);
  gtk_widget_set_size_request (entry11, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label58 = gtk_label_new (_("Abonnement"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed11), label58, 144, 552);
  gtk_widget_set_size_request (label58, 112, 32);
  gtk_misc_set_alignment (GTK_MISC (label58), 0.56, 0.5);
  gtk_misc_set_padding (GTK_MISC (label58), 2, 4);

  label48 = gtk_label_new (_("Jour"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed11), label48, 256, 496);
  gtk_widget_set_size_request (label48, 65, 24);

  label49 = gtk_label_new (_("Mois"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed11), label49, 384, 496);
  gtk_widget_set_size_request (label49, 56, 24);

  label50 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed11), label50, 512, 496);
  gtk_widget_set_size_request (label50, 56, 24);

  label47 = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed11), label47, 104, 496);
  gtk_widget_set_size_request (label47, 152, 24);

  button15 = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed11), button15, 64, 625);
  gtk_widget_set_size_request (button15, 112, 40);

  label53 = gtk_label_new (_("Email"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed11), label53, 187, 450);
  gtk_widget_set_size_request (label53, 64, 27);

  label54 = gtk_label_new (_("T\303\251l\303\251phone"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed11), label54, 159, 400);
  gtk_widget_set_size_request (label54, 88, 27);

  label55 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed11), label55, 190, 350);
  gtk_widget_set_size_request (label55, 56, 27);

  label56 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 176, 300);
  gtk_widget_set_size_request (label56, 64, 27);

  label57 = gtk_label_new (_("Nom"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed11), label57, 188, 250);
  gtk_widget_set_size_request (label57, 56, 27);

  label59 = gtk_label_new (_("ID"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed11), label59, 192, 200);
  gtk_widget_set_size_request (label59, 64, 27);

  label60 = gtk_label_new (_("Ad\303\251hrent"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed11), label60, 352, 72);
  gtk_widget_set_size_request (label60, 84, 17);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox7, 272, 350);
  gtk_widget_set_size_request (combobox7, 250, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Femme"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox6, 272, 552);
  gtk_widget_set_size_request (combobox6, 250, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("3 Mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("6 Mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("1 Ann\303\251e"));

  button16 = gtk_button_new_with_mnemonic (_("Ajouter/Modifier"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed11), button16, 632, 625);
  gtk_widget_set_size_request (button16, 144, 40);

  g_signal_connect_data ((gpointer) button15, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (window3),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window3, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window3, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window3, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window3, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window3, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (window3, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (window3, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (window3, label44, "label44");
  GLADE_HOOKUP_OBJECT (window3, label45, "label45");
  GLADE_HOOKUP_OBJECT (window3, label46, "label46");
  GLADE_HOOKUP_OBJECT (window3, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window3, label58, "label58");
  GLADE_HOOKUP_OBJECT (window3, label48, "label48");
  GLADE_HOOKUP_OBJECT (window3, label49, "label49");
  GLADE_HOOKUP_OBJECT (window3, label50, "label50");
  GLADE_HOOKUP_OBJECT (window3, label47, "label47");
  GLADE_HOOKUP_OBJECT (window3, button15, "button15");
  GLADE_HOOKUP_OBJECT (window3, label53, "label53");
  GLADE_HOOKUP_OBJECT (window3, label54, "label54");
  GLADE_HOOKUP_OBJECT (window3, label55, "label55");
  GLADE_HOOKUP_OBJECT (window3, label56, "label56");
  GLADE_HOOKUP_OBJECT (window3, label57, "label57");
  GLADE_HOOKUP_OBJECT (window3, label59, "label59");
  GLADE_HOOKUP_OBJECT (window3, label60, "label60");
  GLADE_HOOKUP_OBJECT (window3, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (window3, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (window3, button16, "button16");

  return window3;
}

GtkWidget*
create_window4m (void)
{
  GtkWidget *window4m;
  GtkWidget *fixed12mm;
  GtkWidget *entry12mm;
  GtkWidget *label62mm;
  GtkWidget *jj7;
  GtkWidget *jj6;
  GtkWidget *jj8;
  GtkWidget *button18nb;
  GtkWidget *jj9;
  GtkWidget *gg4;
  GtkWidget *gg1;
  GtkWidget *gggg;
  GtkWidget *gg6;
  GtkWidget *gg5;
  GtkWidget *gg3;
  GtkWidget *gg7;
  GtkWidget *jj2;
  GtkWidget *jj1;
  GtkWidget *gg2;
  GtkWidget *jj3;
  GtkWidget *jj4;
  GtkWidget *jj5;

  window4m = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window4m, 850, 700);
  gtk_window_set_title (GTK_WINDOW (window4m), _("remarques"));
  gtk_window_set_position (GTK_WINDOW (window4m), GTK_WIN_POS_CENTER_ALWAYS);

  fixed12mm = gtk_fixed_new ();
  gtk_widget_show (fixed12mm);
  gtk_container_add (GTK_CONTAINER (window4m), fixed12mm);

  entry12mm = gtk_entry_new ();
  gtk_widget_show (entry12mm);
  gtk_fixed_put (GTK_FIXED (fixed12mm), entry12mm, 176, 550);
  gtk_widget_set_size_request (entry12mm, 672, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12mm), 8226);

  label62mm = gtk_label_new (_("<span size=\"xx-large\" color=\"red\">Ajouter Remarques</span>"));
  gtk_widget_show (label62mm);
  gtk_fixed_put (GTK_FIXED (fixed12mm), label62mm, 304, 40);
  gtk_widget_set_size_request (label62mm, 236, 42);
  gtk_label_set_use_markup (GTK_LABEL (label62mm), TRUE);

  jj7 = gtk_label_new ("");
  gtk_widget_show (jj7);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj7, 200, 400);
  gtk_widget_set_size_request (jj7, 150, 30);

  jj6 = gtk_label_new ("");
  gtk_widget_show (jj6);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj6, 200, 350);
  gtk_widget_set_size_request (jj6, 150, 30);

  jj8 = gtk_label_new ("");
  gtk_widget_show (jj8);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj8, 200, 450);
  gtk_widget_set_size_request (jj8, 150, 30);

  button18nb = gtk_button_new_with_mnemonic (_("Ajouter/Modifier"));
  gtk_widget_show (button18nb);
  gtk_fixed_put (GTK_FIXED (fixed12mm), button18nb, 344, 608);
  gtk_widget_set_size_request (button18nb, 130, 61);

  jj9 = gtk_label_new ("");
  gtk_widget_show (jj9);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj9, 200, 500);
  gtk_widget_set_size_request (jj9, 150, 30);

  gg4 = gtk_label_new (_("<span size=\"large\"color=\"blue\">Date de naissance</span>"));
  gtk_widget_show (gg4);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gg4, 32, 300);
  gtk_widget_set_size_request (gg4, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gg4), TRUE);

  gg1 = gtk_label_new (_("<span size=\"large\"color=\"blue\">Remarques</span>"));
  gtk_widget_show (gg1);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gg1, 40, 550);
  gtk_widget_set_size_request (gg1, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gg1), TRUE);

  gggg = gtk_label_new (_("<span size=\"large\"color=\"blue\">IMC</span>"));
  gtk_widget_show (gggg);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gggg, 40, 450);
  gtk_widget_set_size_request (gggg, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gggg), TRUE);

  gg6 = gtk_label_new (_("<span size=\"large\"color=\"blue\">taille</span>"));
  gtk_widget_show (gg6);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gg6, 40, 400);
  gtk_widget_set_size_request (gg6, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gg6), TRUE);

  gg5 = gtk_label_new (_("<span size=\"large\"color=\"blue\">poids</span>"));
  gtk_widget_show (gg5);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gg5, 40, 350);
  gtk_widget_set_size_request (gg5, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gg5), TRUE);

  gg3 = gtk_label_new (_("<span size=\"large\"color=\"blue\">Pr\303\251nom</span>"));
  gtk_widget_show (gg3);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gg3, 40, 250);
  gtk_widget_set_size_request (gg3, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gg3), TRUE);

  gg7 = gtk_label_new (_("<span size=\"large\"color=\"blue\">maladies</span>"));
  gtk_widget_show (gg7);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gg7, 40, 500);
  gtk_widget_set_size_request (gg7, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gg7), TRUE);

  jj2 = gtk_label_new ("");
  gtk_widget_show (jj2);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj2, 200, 250);
  gtk_widget_set_size_request (jj2, 150, 30);

  jj1 = gtk_label_new ("");
  gtk_widget_show (jj1);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj1, 200, 200);
  gtk_widget_set_size_request (jj1, 150, 30);

  gg2 = gtk_label_new (_("<span size=\"large\"color=\"blue\">Nom</span>"));
  gtk_widget_show (gg2);
  gtk_fixed_put (GTK_FIXED (fixed12mm), gg2, 40, 200);
  gtk_widget_set_size_request (gg2, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (gg2), TRUE);

  jj3 = gtk_label_new (_("a"));
  gtk_widget_show (jj3);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj3, 208, 296);
  gtk_widget_set_size_request (jj3, 40, 40);

  jj4 = gtk_label_new (_("a"));
  gtk_widget_show (jj4);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj4, 280, 296);
  gtk_widget_set_size_request (jj4, 40, 40);

  jj5 = gtk_label_new (_("a"));
  gtk_widget_show (jj5);
  gtk_fixed_put (GTK_FIXED (fixed12mm), jj5, 360, 296);
  gtk_widget_set_size_request (jj5, 40, 40);

  g_signal_connect ((gpointer) button18nb, "clicked",
                    G_CALLBACK (on_button18nb_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4m, window4m, "window4m");
  GLADE_HOOKUP_OBJECT (window4m, fixed12mm, "fixed12mm");
  GLADE_HOOKUP_OBJECT (window4m, entry12mm, "entry12mm");
  GLADE_HOOKUP_OBJECT (window4m, label62mm, "label62mm");
  GLADE_HOOKUP_OBJECT (window4m, jj7, "jj7");
  GLADE_HOOKUP_OBJECT (window4m, jj6, "jj6");
  GLADE_HOOKUP_OBJECT (window4m, jj8, "jj8");
  GLADE_HOOKUP_OBJECT (window4m, button18nb, "button18nb");
  GLADE_HOOKUP_OBJECT (window4m, jj9, "jj9");
  GLADE_HOOKUP_OBJECT (window4m, gg4, "gg4");
  GLADE_HOOKUP_OBJECT (window4m, gg1, "gg1");
  GLADE_HOOKUP_OBJECT (window4m, gggg, "gggg");
  GLADE_HOOKUP_OBJECT (window4m, gg6, "gg6");
  GLADE_HOOKUP_OBJECT (window4m, gg5, "gg5");
  GLADE_HOOKUP_OBJECT (window4m, gg3, "gg3");
  GLADE_HOOKUP_OBJECT (window4m, gg7, "gg7");
  GLADE_HOOKUP_OBJECT (window4m, jj2, "jj2");
  GLADE_HOOKUP_OBJECT (window4m, jj1, "jj1");
  GLADE_HOOKUP_OBJECT (window4m, gg2, "gg2");
  GLADE_HOOKUP_OBJECT (window4m, jj3, "jj3");
  GLADE_HOOKUP_OBJECT (window4m, jj4, "jj4");
  GLADE_HOOKUP_OBJECT (window4m, jj5, "jj5");

  return window4m;
}

