/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_bienvenue (void);
GtkWidget* create_window2 (void);
GtkWidget* create_admin1 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4m (void);
